name: Python CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_prepare
      - name: Run mypy
        run: poetry run mypy
